#!/usr/bin/bash

# Roboshop - frontened setup

source common.sh

component=frontened

echo installing nginx
yum install nginx -y &>>${Log}
statuscheck

download

echo clean old content
cd /usr/share/nginx/html && rm -rf *
statuscheck

echo extract download content
unzip -o /tmp/frontend.zip &>>${Log} && mv frontend-main/static/* . && mv frontend-main/localhost.conf /etc/nginx/default.d/roboshop.conf
statuscheck

echo start nginx service
systemctl restrart nginx &>>${Log} && systemctl enable nginx &>>${Log}





